### ISSUE TITLE
Aot compilation returns errors

### ISSUE THREAD

**Issue by tauciokas** [FabianGosebrink/ASPNET-ASPNETCore-Angular-Webpack#7]
Hey,

I was following your tutorial on aot compilation from [here](https://offering.solutions/blog/articles/2017/02/08/angular-2-ahead-of-time-aot-compilation-lazy-loading-treeshaking-webpack/) but get these errors after running` "node_modules/.bin/ngc" -p tsconfig-aot.json` would you know why? 

```
Error at C:/wamp/www/stiqqs/ui/node_modules/typescript/lib/lib.es2015.core.d.ts:21:14: Duplicate identifier 'PropertyKey'.
Error at C:/wamp/www/stiqqs/ui/src/app/views/ad-listing/ad-listing.component.ts:28:9: Object literal's property 'search' implicitly has an 'any' type.
Error at C:/wamp/www/stiqqs/ui/src/app/views/ad-listing/ad-listing.component.ts:29:9: Object literal's property 'city' implicitly has an 'any' type.
Error at C:/wamp/www/stiqqs/ui/src/app/views/ad-listing/ad-listing.component.ts:30:9: Object literal's property 'category' implicitly has an 'any' type.
Error at C:/wamp/www/stiqqs/ui/src/app/views/ad-detail/ad-detail.component.ts:164:49: Parameter 'el' implicitly has an 'any' type.
Error at C:/wamp/www/stiqqs/ui/src/app/views/messenger/messenger.component.ts:46:51: Parameter 'event' implicitly has an 'any' type.
Error at C:/wamp/www/stiqqs/ui/src/app/views/dashboard/dashboard-tabs/bids/bids.component.ts:37:57: Parameter 'bid' implicitly has an 'any' type.
Error at C:/wamp/www/stiqqs/ui/src/app/views/dashboard/dashboard-tabs/bids/bids.component.ts:38:61: Parameter 'bid' implicitly has an 'any' type.
Error at C:/wamp/www/stiqqs/ui/src/app/views/dashboard/dashboard-tabs/bids/bids.component.ts:39:57: Parameter 'bid' implicitly has an 'any' type.
Error at C:/wamp/www/stiqqs/ui/src/app/views/dashboard/dashboard-tabs/messages/messages.component.ts:27:51: Parameter 'event' implicitly has an 'any' type.
Error at C:/wamp/www/stiqqs/ui/src/app/views/dashboard/dashboard-tabs/messages/messages.component.ts:55:51: Parameter 'element' implicitly has an 'any' type.
Error at C:/wamp/www/stiqqs/ui/src/app/views/dashboard/dashboard-tabs/ad-list/ad-list.component.ts:37:56: Parameter 'ad' implicitly has an 'any' type.
Error at C:/wamp/www/stiqqs/ui/src/app/views/dashboard/dashboard-tabs/ad-list/ad-list.component.ts:38:60: Parameter 'ad' implicitly has an 'any' type.
Error at C:/wamp/www/stiqqs/ui/node_modules/@types/es6-shim/index.d.ts:7:14: Duplicate identifier 'PropertyKey'.
Error at C:/wamp/www/stiqqs/ui/node_modules/@types/es6-shim/index.d.ts:11:5: All declarations of 'value' must have identical modifiers.
Error at C:/wamp/www/stiqqs/ui/node_modules/@types/es6-shim/index.d.ts:248:5: All declarations of 'EPSILON' must have identical modifiers.
Error at C:/wamp/www/stiqqs/ui/node_modules/@types/es6-shim/index.d.ts:283:5: All declarations of 'MAX_SAFE_INTEGER' must have identical modifiers.
Error at C:/wamp/www/stiqqs/ui/node_modules/@types/es6-shim/index.d.ts:290:5: All declarations of 'MIN_SAFE_INTEGER' must have identical modifiers.
Error at C:/wamp/www/stiqqs/ui/node_modules/@types/es6-shim/index.d.ts:346:5: All declarations of 'flags' must have identical modifiers.
Error at C:/wamp/www/stiqqs/ui/node_modules/@types/es6-shim/index.d.ts:498:5: All declarations of 'prototype' must have identical modifiers.
Error at C:/wamp/www/stiqqs/ui/node_modules/@types/es6-shim/index.d.ts:561:5: All declarations of 'size' must have identical modifiers.
Error at C:/wamp/www/stiqqs/ui/node_modules/@types/es6-shim/index.d.ts:570:5: All declarations of 'prototype' must have identical modifiers.
Error at C:/wamp/www/stiqqs/ui/node_modules/@types/es6-shim/index.d.ts:581:5: All declarations of 'size' must have identical modifiers.
Error at C:/wamp/www/stiqqs/ui/node_modules/@types/es6-shim/index.d.ts:591:5: All declarations of 'prototype' must have identical modifiers.
Error at C:/wamp/www/stiqqs/ui/node_modules/@types/es6-shim/index.d.ts:606:5: Subsequent variable declarations must have the same type.  Variable 'prototype' must be of type 'WeakMap<object, any>',
 but here has type 'WeakMap<any, any>'.
Error at C:/wamp/www/stiqqs/ui/node_modules/@types/es6-shim/index.d.ts:606:5: All declarations of 'prototype' must have identical modifiers.
Error at C:/wamp/www/stiqqs/ui/node_modules/@types/es6-shim/index.d.ts:620:5: Subsequent variable declarations must have the same type.  Variable 'prototype' must be of type 'WeakSet<object>', but
here has type 'WeakSet<any>'.
Error at C:/wamp/www/stiqqs/ui/node_modules/@types/es6-shim/index.d.ts:620:5: All declarations of 'prototype' must have identical modifiers.
```

Fair enough i can deal with errors that are in `ui/src/app/` but the node module errors is something i can't just fix. Here is my package.json

```
{
  "name": "stiqqs",
  "version": "1.0.0",
  "description": "",
  "license": "",
  "dependencies": {
    "@angular/animations": "^4.3.6",
    "@angular/common": "^4.1.0",
    "@angular/compiler": "^4.1.0",
    "@angular/compiler-cli": "^4.4.0-RC.0",
    "@angular/core": "^4.1.0",
    "@angular/forms": "^4.1.0",
    "@angular/http": "^4.1.0",
    "@angular/platform-browser": "^4.1.0",
    "@angular/platform-browser-dynamic": "^4.1.0",
    "@angular/platform-server": "^4.4.0-RC.0",
    "@angular/router": "^4.1.0",
    "@types/node": "^7.0.16",
    "angular2-notifications": "^0.7.3",
    "core-js": "*",
    "gulp": "github:gulpjs/gulp#4ed9a4a3275559c73a396eff7e1fde3824951ebb",
    "gulp-hub": "github:frankwallis/gulp-hub#d461b9c700df9010d0a8694e4af1fb96d9f38bf4",
    "hammerjs": "^2.0.8",
    "ng2-completer": "^1.4.0",
    "ng2-metadata": "^1.4.2-final",
    "ngx-modal": "0.0.29",
    "ngx-pagination": "^3.0.0",
    "rxjs": "^5.3.1",
    "time-ago-pipe": "^1.2.1",
    "tslint-loader": "^3.5.3",
    "typescript": "^2.3.2",
    "webpack": "^2.5.0",
    "zone.js": "^0.8.10"
  },
  "devDependencies": {
    "@types/es6-shim": "^0.31.32",
    "@types/jasmine": "^2.5.43",
    "@types/node": "^7.0.5",
    "autoprefixer": "^6.7.3",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^6.3.2",
    "browser-sync": "^2.18.8",
    "browser-sync-spa": "^1.0.3",
    "compression-webpack-plugin": "^0.4.0",
    "css-loader": "^0.26.1",
    "del": "^2.2.2",
    "es6-shim": "^0.35.3",
    "eslint": "^3.15.0",
    "eslint-config-xo-space": "^0.15.0",
    "eslint-loader": "^1.6.1",
    "eslint-plugin-babel": "^4.0.1",
    "extract-text-webpack-plugin": "^2.0.0-rc.3",
    "gulp": "gulpjs/gulp#4ed9a4a3275559c73a396eff7e1fde3824951ebb",
    "gulp-filter": "^5.0.0",
    "gulp-hub": "frankwallis/gulp-hub#d461b9c700df9010d0a8694e4af1fb96d9f38bf4",
    "gulp-sass": "^3.1.0",
    "gulp-util": "^3.0.8",
    "html-loader": "^0.4.4",
    "html-webpack-plugin": "^2.28.0",
    "json-loader": "^0.5.4",
    "node-sass": "^4.5.0",
    "postcss-loader": "^1.3.1",
    "rimraf": "^2.5.1",
    "sass-loader": "^6.0.1",
    "style-loader": "^0.13.1",
    "ts-loader": "^2.0.0",
    "tslint": "^4.4.2",
    "tslint-loader": "^3.4.2",
    "typescript": "^2.1.0",
    "webpack": "^2.5.0",
    "webpack-deploy": "github:productboard/webpack-deploy",
    "webpack-fail-plugin": "^1.0.5"
  },
  "scripts": {
    "build": "rimraf dist && webpack --progress --profile --bail --config ./conf/webpack-dist.conf.js && cp -r ./src/css ./dist && cp -r ./src/img ./dist && mkdir -p ./dist/app/views && cp -r ./src/app/views/* ./dist/app/views/",
    "serve": "gulp serve watch",
    "serve:dist": "gulp serve:dist",
    "test": "gulp test",
    "test:auto": "gulp test:auto",
    "deploy": "webpack -p --config ./conf/webpack-dist.conf.js"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "browser": true,
      "jasmine": true
    },
    "parser": "babel-eslint",
    "extends": [
      "xo-space/esnext"
    ]
  },
  "repository": {}
}
```
Can you spot if I'm doing something wrong? p.s tsconfig-aot.json is exactly the same as in the tutorial

**Comment by FabianGosebrink** [comment]
Yeah, it seems like you are using the any type not explicitly. https://stackoverflow.com/questions/42065818/angular2-aot-compile-what-does-implicitly-has-an-any-type-mean-and-how-to-cor/42066760#42066760

**Comment by tauciokas** [comment]
Ok cheers, I'll give it a go.

**Comment by FabianGosebrink** [comment]
closing as this got no feedback anymore
